experiment:
    type: 'cv'  # 'single', 'cv'
    n_folds: 10  # number of folds to use if cv is active
    np_random_seed: 52
    years: [1, 2, 3, 4, 5]
    shuffle_data: True
    test_share: 0.1
    algorithm: 'rf'
imputer_params:
    strategy: 'min'  # 'mean', 'min'
    new_features: '1-hot'  # False, 'sum', '1-hot'
    only_nan_data: False  # True, False
processor_params:
    normalize: True
    max_nan_share: 1.0
algo_params:
    n_estimators: 100
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    warm_start: False
    criterion: 'entropy'
    bootstrap: False
    oob_score: False
    max_features: 'auto'
    max_depth: Null
    max_leaf_nodes: Null
    class_weight: Null
    #min_impurity_split: None
analysis:
    print_results: ['classification_report', 'log_loss', 'accuracy', 'roc_auc']
    plot_roc: True
